# YOLO 四分类特殊车牌微调数据集
# 训练超参数独立维护在 yolo_finetune_train.yaml。
path: D:/Yolo_LPR_RK3568_FPGA_Project/1_PC_Training/datasets/yolo_finetune_special
train: images/train
val: images/val
test: images/test

names:
  0: blue
  1: green
  2: yellow_single
  3: other
